version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: employee_management_db
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_SERVICE: gmail
      SMTP_MAIL: afdulrohmat03@gmail.com
      SMTP_PASSWORD: usvk qjbz ddhd qebx
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
